services:
  web:
    build: .
    container_name: hackernews_web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: hackernews_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: hackernews_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
