services:
  web:
    build: .
    container_name: hackernews_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app  # /app dizinini PYTHONPATH olarak ekliyoruz

  db:
    image: postgres:14
    container_name: hackernews_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: hackernews_redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app  # /app dizinini PYTHONPATH olarak ekliyoruz


volumes:
  postgres_data:
